kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: nfs-client-provisioner
    chart: nfs-client-provisioner-1.2.9
    heritage: Helm
    release: nfs-client-provisioner-1598608233
  name: leader-locking-nfs-client-provisioner-1598608233
subjects:
  - kind: ServiceAccount
    name: nfs-client-provisioner-1598608233
    namespace: nfs
roleRef:
  kind: Role
  name: leader-locking-nfs-client-provisioner-1598608233
  apiGroup: rbac.authorization.k8s.io