apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: nfs-client-provisioner
    chart: nfs-client-provisioner-1.2.9
    heritage: Helm
    release: nfs-client-provisioner-1598608233
  name: nfs-client-provisioner-1598608233