apiVersion: v1
kind: Service
metadata:
  labels:
    app: rook-nfs
  name: rook-nfs-external
  namespace: rook-nfs-system
spec:
  ports:
    - name: nfs
      port: 2049
      protocol: TCP
      targetPort: 2049
    - name: rpc
      port: 111
      protocol: TCP
      targetPort: 111
  selector:
    app: rook-nfs
  sessionAffinity: None
  type: ExternalName
  externalName: rook-nfs.rook-nfs-system.svc.cluster.local