apiVersion: specs.smi-spec.io/v1alpha3
kind: HTTPRouteGroup
metadata:
  name: http-everything
  namespace: whoami
spec:
  matches:
    - name: everything
      pathRegex: ".*"
      methods: ["*"]

---
kind: TrafficTarget
apiVersion: access.smi-spec.io/v1alpha2
metadata:
  name: whatever
  namespace: whoami
spec:
  destination:
    kind: ServiceAccount
    name: whoami-server
    namespace: whoami
    port: "80"
  rules:
    - kind: HTTPRouteGroup
      name: http-everything
      matches:
        - everything
  sources:
    - kind: ServiceAccount
      name: whoami-client
      namespace: whoami
---
apiVersion: specs.smi-spec.io/v1alpha3
kind: TCPRoute
metadata:
  name: my-tcp-route
  namespace: whoami
spec: {}