apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev
namePrefix: dev-
#commonLabels:
#  instance: rba


patchesStrategicMerge:
- redis-master-deployment.yaml
resources:
- ../../common-base