apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-pv
  labels:
    type: local
spec:
  storageClassName: vault-local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"