kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data
  annotations:
    volume.beta.kubernetes.io/storage-class: px-shared-sc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 4Gi