kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-pv-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: manual
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi