apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: service
  source:
    repoURL: https://github.com/KKisilevsky/infra.git
    targetRevision: HEAD
    path: redis/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated: {}