apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rba-app
  namespace: argocd 
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: tenant
  source:
    path: vc-project/dev
    repoURL: https://github.com/KKisilevsky/infra.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true