apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/KKisilevsky/infra.git
    targetRevision: HEAD
    path: cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  ignoreDifferences:
  - group: apiextensions.k8s.io
    jsonPointers:
    - /status
    kind: CustomResourceDefinition
  - group: admissionregistration.k8s.io
    jsonPointers:
    - /status
    kind: ValidatingWebhookConfiguration