apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd  
spec:
    project: default
    source:
        repoURL: 'https://github.com/KKisilevsky/infra.git'
        path: prometheus-operator
        targetRevision: HEAD
    destination:
        server: 'https://kubernetes.default.svc'
        namespace: prometheus-operator
    ignoreDifferences:
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
        jsonPointers:
          - /metadata/annotations
          - /metadata/labels
          - /spec/validation
      - group: admissionregistration.k8s.io
        kind: MutatingWebhookConfiguration
        jsonPointers:
          - /webhooks
      - group: admissionregistration.k8s.io
        kind: ValidatingWebhookConfiguration
        jsonPointers:
          - /webhooks