apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd  
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 9.4.4
    helm:
        parameters:
        - name: prometheusOperator.admissionWebhooks.enabled
          value: 'false'
        - name: prometheusOperator.tlsProxy.enabled
          value: 'false'
        - name: prometheusOperator.createCustomResource
          value: 'false'
    chart: kube-prometheus-stack
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prometheus-stack
  syncPolicy: {}

