apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: httpbin-deny
 namespace: sas
spec:
 selector:
   matchLabels:
     app: error-page 
     version: v1
 action: DENY
 rules:
 - from:
   - source:
       notNamespaces: ["sas"]