apiVersion: v1
kind: PersistentVolume
metadata:
  name: stage-modules-pv-volume 
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  nfs:
    server: 10.240.0.4
    path: /srv/nfs/data/stage-modules-pv-volume