apiVersion: v1
kind: PersistentVolume
metadata:
  name: cms-pv-volume
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
  nfs:
    server: 10.240.0.4
    path: /srv/nfs/data