# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: cms-pv-volume
# spec:
#   storageClassName: "rook-nfs-share1"
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 100Mi
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cms-pv-volume
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
