apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: modules-pv-volume
spec:
  storageClassName: "rook-nfs-share1"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi