apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: platform
  template:
    metadata:
      labels:
        app: platform
    spec:
      containers:
      - name: vc-platform-web      
        image: virtocommerce/platform:v3-preview6-dev
        env: 
          - name: VC_DBSERVER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mssql
                key: SA_PASSWORD
          - name: REDIS_PASS
            valueFrom:
              secretKeyRef:
                name: redis
                key: REDIS_PASS      
          - name: ConnectionStrings__VirtoCommerce
            value: "Server=tcp:mssql-deployment,1433;;Initial Catalog=VirtoCommerce3docker;Persist Security Info=True;User ID=sa;Password=$(VC_DBSERVER_PASSWORD);MultipleActiveResultSets=False;Connect Timeout=120"
          - name: ConnectionStrings__RedisConnectionString
            value: "redis-master.redis:6379,password=$(REDIS_PASS),ssl=False,abortConnect=False"  
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/opt/virtocommerce/platform/wwwroot/cms-content"
          name: cms-content-data
        - mountPath: "/opt/virtocommerce/platform/Modules"
          name: modules-data
      volumes:
      - name: cms-content-data
        persistentVolumeClaim:
          claimName: cms-content-volume
      - name: modules-data
        emptyDir: {}
        #persistentVolumeClaim:
        #  claimName: modules-volume       
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate