apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: platform
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "myapp"
        vault.hashicorp.com/agent-inject-secret-db: "secret_dev/mssql"
        vault.hashicorp.com/agent-inject-template-db: |
          {{- with secret "secret_dev/mssql" -}}
          export ConnectionStrings__VirtoCommerce="Server=tcp:mssql-deployment,1433;;Initial Catalog=VirtoCommerce3docker;Persist Security Info=True;User ID=sa;Password={{ .Data.data.SA_PASSWORD }};MultipleActiveResultSets=False;Connect Timeout=120"
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-redis: "secret_dev/redis"
        vault.hashicorp.com/agent-inject-template-redis: |
          {{- with secret "secret_dev/redis" -}}
          export ConnectionStrings__RedisConnectionString="redis-master.redis:6379,password={{ .Data.data.REDIS_PASS }},ssl=False,abortConnect=False"
          {{- end }}
      labels:
        app: platform
    spec:
      serviceAccountName: app
      containers:
      - name: vc-platform-web      
        image: virtocommerce/platform:v3-preview6-dev
        command:
          - "/bin/bash"
          - "-c"
        args:
          - "cat /vault/secrets/db >> /vault/secrets/config;
            cat /vault/secrets/redis >> /vault/secrets/config;
            source /vault/secrets/config && dotnet VirtoCommerce.Platform.Web.dll" 
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/opt/virtocommerce/platform/wwwroot/cms-content"
          name: cms-content-data
        - mountPath: "/opt/virtocommerce/platform/Modules"
          name: modules-data
      volumes:
      - name: cms-content-data
        persistentVolumeClaim:
          claimName: cms-pv-volume
      - name: modules-data
        persistentVolumeClaim:
          claimName: modules-pv-volume     
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app
  labels:
    app: platform