# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: minijob
# spec:
#   backoffLimit: 5
#   activeDeadlineSeconds: 600
#   volumes:
#     - name: modules-data
#       persistentVolumeClaim:
#         claimName: modules-pv-volume
#   template:
#     spec:
#       containers:
#       - name: minijob
#         image: apline
#         command: ["touch 1 /mnt/data"]
#         volumeMounts:
#             - mountPath: "/mnt/data"
#               name: modules-data
#       restartPolicy: Never
apiVersion: v1
kind: Pod
metadata:
    name: uploader
spec:
    containers:
      - name: minijob
        image: docker.pkg.github.com/virtocommerce/vc-deploy-containers/platform-installer:latest
        command:
          - "/bin/bash"
          - "-c"
        args:
          - "python3 install-modules.py $(VC_PLATFORM_MODULES_CONFIG) /data"
        volumeMounts:
        - name: modules-data
          mountPath: /data
        envFrom:
          - configMapRef:
              name: modules-cm 
    volumes:
     - name: modules-data
       persistentVolumeClaim:
         claimName: modules-pv-volume